### ISSUE TITLE
Support ES6

### ISSUE THREAD

**Issue by wyaeld** [arkency/scaffold-to-react#1]
Just a suggestion, but we are seeing a lot more applications go down the ES6 with Babel route, than trying to work with React.js stuck on current javascript.

If you are trying to show an 'ideal' scaffold, then I'd suggest its either worthwhile to include that, or explain  in the readme your belief on why not to.

If using react-rails, it really only needs the 2 sprockets gems and just works.

**Comment by Killavus** [comment]
Hello,

Thanks for your contribution. Indeed, ES6 would be a more 'ideal' technology for this scaffold.

I wanted to show a really minimal example here - adding ES6 would force me to add yet another part of config to support ES6 in Sprockets.

Do you have a simple way to do it?

**Comment by wyaeld** [comment]
I do it according to here https://babeljs.io/docs/setup/#rails

Just the Gemfile lines + a `require "sprockets/es6"`, nothing more.  Your existing `.jsx` file extensions will be the trigger

**Comment by voter101** [comment]
Hey,

I don't know much about project structure, but using this gem may not be that easy. I wrote a blogpost about it before: http://blog.arkency.com/2015/05/start-using-es6-with-rails-today/

**Comment by Killavus** [comment]
I'll try to integrate it later. You can also propose a pull request if you are experienced in this kind of ES6 integration. We've experienced problems with this approach before - maybe with newer version of gems (like react-rails) it is possible in an easy way.

**Comment by Killavus** [comment]
Closing for now.
